#!/bin/bash

TRSH_SHELL=$SHELL
SHELL_NAME=${TRSH_SHELL##/bin/}
for rc in $(ls /etc/*rc* | grep $SHELL_NAME | grep -vP "\.bac$" | grep -vP "\.new$" )
do
	RC_FILE=$rc
done
if [ -z $RC_FILE ]
then
	echo "ERROR! No RC FILE Found"
	exit -127
fi

if [[ $SHELL_NAME -eq "bash" ]]
then
	ALIAS_RM="alias rm=\"/usr/bin/trsh.pl\" # TRSH"
	ALIAS_UNDO="alias undo=\"/usr/bin/trsh.pl -u\" # TRSH"
elif [[ $SHELL_NAME -eq "csh" ]] || [[ $SHELL_NAME -eq "tcsh" ]]
then
	ALIAS_RM="alias rm \"/usr/bin/trsh.pl\" # TRSH"
	ALIAS_UNDO="alias undo \"/usr/bin/trsh.pl -u\" # TRSH"
else
	exit -127
fi
sed -e '/.* # TRSH/d' $RC_FILE > $RC_FILE.new
echo $ALIAS_RM >> $RC_FILE.new
echo $ALIAS_UNDO >> $RC_FILE.new
mv $RC_FILE.new $RC_FILE
