#!/bin/bash

TRSH_SHELL=$SHELL
SHELL_NAME=${TRSH_SHELL##/bin/}
for rc in $( ls /etc/*rc* | grep $SHELL_NAME | grep -vP "\.bac$" | grep -vP "\.new$" )
do
	RC_FILE=$rc
done
if [ -z $RC_FILE ]
then
	echo "ERROR! No RC FILE Found"
	exit -127
fi

sed -e '/.* # TRSH/d' $RC_FILE > $RC_FILE.new
mv $RC_FILE.new $RC_FILE

exit 0

