######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 12 22:15:41 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += trsh_interface.h
FORMS += ktrsh.ui yesNo.ui restoreDialog.ui 
SOURCES += main.cpp
